/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;
import java.awt.*;
import java.awt.event.ActionListener;
import javax.swing.*;

/**
 *
 * @author luuxu
 */
public class Form_zMain extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Form_zMain.class.getName());


    
    private JPanel jpn_menuFull;
    private JPanel jpn_menuKhach;
    /**
     * Creates new form Form_Trangchu
     */
    private int quyenUser = 0;
    public Form_zMain() {
        this(0); // mặc định là nhân viên khi chạy trực tiếp
    }
    
    public Form_zMain(int quyen) {
        initComponents();
        this.setLocationRelativeTo(this);
        this.setExtendedState(MAXIMIZED_BOTH);
        this.quyenUser = quyen;
        
        jpn_header.setBackground(new Color(41, 128, 185));
        lbl_tieude.setForeground(Color.WHITE);
        jpn_west.setPreferredSize(new Dimension(265, 520));
        jpn_center.setBackground(Color.WHITE);

        
        modifyMenu();
        //add cac panel con
        add_Panel();
        // Tạo 2 menu bằng CardLayout
        setupMenuCardLayout();
        // Hiển thị đúng menu theo quyền + mở trang chủ
        showMenuByQuyen();
        
        show_Panel("TRANGCHU");
    }
    
    private void modifyMenu(){
        jpn_west.setBackground(new Color(52, 73, 94));   // menu nền
        jpn_west.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 10, 20, 10));

        customizeButton(btn_trangchu);
        customizeButton(btn_datphong);
        customizeButton(btn_quanlyphong);
        customizeButton(btn_quanlydatphong);
        customizeButton(btn_quanlykhachhang);
        customizeButton(btn_quanlydichvu);
        customizeButton(btn_dangxuat);
        customizeButton(btn_thoat);
    }
    private void customizeButton(javax.swing.JButton btn){
        btn.setFont(new Font("Arial",Font.PLAIN, 14));
        btn.setForeground(Color.WHITE);
        btn.setBackground(new Color(52, 73, 94));

        btn.setFocusPainted(false);
        btn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        btn.setCursor(new Cursor(Cursor.HAND_CURSOR));
        btn.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 15, 10, 15));

        //btn.setPreferredSize(new Dimension(230, 45));
        //btn.setMaximumSize(new Dimension(230, 45));
        ///btn.setMinimumSize(new Dimension(230, 45));
        
         // Hiệu ứng hover
        btn.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn.setBackground(new Color(41, 128, 185));
            }

            @Override
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn.setBackground(new Color(52, 73, 94));
            }
        });
    }
    
    //add cac panel vao frame
    private void add_Panel(){
        jpn_center.add(new Form_Trangchu(), "TRANGCHU");
        jpn_center.add(new Form_Datphong(), "DATPHONG");
        jpn_center.add(new Form_Quanlyphong(), "QUANLYPHONG");
        jpn_center.add(new Form_Quanlydatphong(), "QUANLYDATPHONG");
        jpn_center.add(new Form_Quanlykhachhang(), "QUANLYKHACHHANG");
        jpn_center.add(new Form_Quanlydichvu(), "QUANLYDICHVU");

    }
    //hienthi cac panle
    private void show_Panel(String name) {
        CardLayout cl = (CardLayout) jpn_center.getLayout();
        cl.show(jpn_center, name);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpn_header = new javax.swing.JPanel();
        lbl_tieude = new javax.swing.JLabel();
        jpn_west = new javax.swing.JPanel();
        btn_trangchu = new javax.swing.JButton();
        btn_datphong = new javax.swing.JButton();
        btn_quanlyphong = new javax.swing.JButton();
        btn_quanlydatphong = new javax.swing.JButton();
        btn_quanlykhachhang = new javax.swing.JButton();
        btn_quanlydichvu = new javax.swing.JButton();
        btn_dangxuat = new javax.swing.JButton();
        btn_thoat = new javax.swing.JButton();
        jpn_center = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jpn_header.setPreferredSize(new java.awt.Dimension(860, 80));

        lbl_tieude.setBackground(new java.awt.Color(0, 153, 204));
        lbl_tieude.setFont(new java.awt.Font("Arial", 1, 28)); // NOI18N
        lbl_tieude.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_tieude.setText("HỆ THỐNG QUẢN LÝ KHÁCH SẠN ");

        javax.swing.GroupLayout jpn_headerLayout = new javax.swing.GroupLayout(jpn_header);
        jpn_header.setLayout(jpn_headerLayout);
        jpn_headerLayout.setHorizontalGroup(
            jpn_headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_tieude, javax.swing.GroupLayout.DEFAULT_SIZE, 848, Short.MAX_VALUE)
        );
        jpn_headerLayout.setVerticalGroup(
            jpn_headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_tieude, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
        );

        getContentPane().add(jpn_header, java.awt.BorderLayout.PAGE_START);

        jpn_west.setPreferredSize(new java.awt.Dimension(250, 520));

        btn_trangchu.setText("TRANG CHỦ");
        btn_trangchu.setMaximumSize(new java.awt.Dimension(230, 45));
        btn_trangchu.setMinimumSize(new java.awt.Dimension(230, 45));
        btn_trangchu.setPreferredSize(new java.awt.Dimension(230, 45));
        btn_trangchu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_trangchuActionPerformed(evt);
            }
        });

        btn_datphong.setText("ĐẶT PHÒNG");
        btn_datphong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_datphongActionPerformed(evt);
            }
        });

        btn_quanlyphong.setText("QUẢN LÝ PHÒNG");
        btn_quanlyphong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_quanlyphongActionPerformed(evt);
            }
        });

        btn_quanlydatphong.setText("QUẢN LÝ ĐẶT PHÒNG");
        btn_quanlydatphong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_quanlydatphongActionPerformed(evt);
            }
        });

        btn_quanlykhachhang.setText("QUẢN LÝ KHÁCH HÀNG");
        btn_quanlykhachhang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_quanlykhachhangActionPerformed(evt);
            }
        });

        btn_quanlydichvu.setText("QUẢN LÝ DỊCH VỤ");
        btn_quanlydichvu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_quanlydichvuActionPerformed(evt);
            }
        });

        btn_dangxuat.setText("ĐĂNG XUẤT");
        btn_dangxuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_dangxuatActionPerformed(evt);
            }
        });

        btn_thoat.setText("THOÁT HỆ THỐNG");
        btn_thoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_thoatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpn_westLayout = new javax.swing.GroupLayout(jpn_west);
        jpn_west.setLayout(jpn_westLayout);
        jpn_westLayout.setHorizontalGroup(
            jpn_westLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpn_westLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jpn_westLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_quanlydatphong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_quanlyphong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_trangchu, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_datphong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_quanlykhachhang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_quanlydichvu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_dangxuat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_thoat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jpn_westLayout.setVerticalGroup(
            jpn_westLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpn_westLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(btn_trangchu, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_datphong, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_quanlyphong, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_quanlydatphong, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_quanlykhachhang, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_quanlydichvu, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_dangxuat, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_thoat, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(115, Short.MAX_VALUE))
        );

        getContentPane().add(jpn_west, java.awt.BorderLayout.LINE_START);

        jpn_center.setLayout(new java.awt.CardLayout());
        getContentPane().add(jpn_center, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_trangchuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_trangchuActionPerformed
        show_Panel("TRANGCHU");
        
    }//GEN-LAST:event_btn_trangchuActionPerformed

    private void btn_quanlyphongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_quanlyphongActionPerformed
        show_Panel("QUANLYPHONG");
    }//GEN-LAST:event_btn_quanlyphongActionPerformed

    private void btn_quanlykhachhangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_quanlykhachhangActionPerformed
        show_Panel("QUANLYKHACHHANG");
    }//GEN-LAST:event_btn_quanlykhachhangActionPerformed

    private void btn_quanlydichvuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_quanlydichvuActionPerformed
        show_Panel("QUANLYDICHVU");
    }//GEN-LAST:event_btn_quanlydichvuActionPerformed

    private void btn_dangxuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_dangxuatActionPerformed
         int confirm = JOptionPane.showConfirmDialog(
                this,
                "Bạn có chắc chắn muốn đăng xuất?",
                "Xác nhận",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE
        );
        if (confirm == JOptionPane.YES_OPTION) {
            new Form_DangNhap().setVisible(true);
            this.dispose();
        }else{
            
        }
    }//GEN-LAST:event_btn_dangxuatActionPerformed

    private void btn_datphongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_datphongActionPerformed
        show_Panel("DATPHONG");
    }//GEN-LAST:event_btn_datphongActionPerformed

    private void btn_quanlydatphongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_quanlydatphongActionPerformed
        show_Panel("QUANLYDATPHONG");
    }//GEN-LAST:event_btn_quanlydatphongActionPerformed

    private void btn_thoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_thoatActionPerformed
        int choice = JOptionPane.showConfirmDialog(this, 
                "Bạn có chắc muốn thoát hệ thống không ?",
                "Kết thúc",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE);
        if(choice==JOptionPane.YES_OPTION){
            System.exit(0);
        }else{
            
        }
    }//GEN-LAST:event_btn_thoatActionPerformed
    
    //lam lai toan bo jpn_west(menu) de phan quyen
    private void setupMenuCardLayout() {
         // Xóa layout cũ
        jpn_west.removeAll();
        jpn_west.setLayout(new CardLayout());
        jpn_west.setBackground(new Color(52, 73, 94));
        jpn_west.setBorder(BorderFactory.createEmptyBorder(20, 15, 20, 15));

        // MENU FULL (NHÂN VIÊN)
        JPanel jpn_menuFull = new JPanel();
        jpn_menuFull.setOpaque(false);
        jpn_menuFull.setLayout(new BoxLayout(jpn_menuFull, BoxLayout.Y_AXIS));

        addButtonWithSpace(jpn_menuFull, btn_trangchu);
        addButtonWithSpace(jpn_menuFull, btn_datphong);
        addButtonWithSpace(jpn_menuFull, btn_quanlyphong);
        addButtonWithSpace(jpn_menuFull, btn_quanlydatphong);
        addButtonWithSpace(jpn_menuFull, btn_quanlykhachhang);
        addButtonWithSpace(jpn_menuFull, btn_quanlydichvu);
        addButtonWithSpace(jpn_menuFull, btn_dangxuat);
        addButtonWithSpace(jpn_menuFull, btn_thoat);
        jpn_menuFull.add(Box.createVerticalGlue());

        // MENU KHÁCH HÀNG
        JPanel jpn_menuKhach = new JPanel();
        jpn_menuKhach.setOpaque(false);
        jpn_menuKhach.setLayout(new BoxLayout(jpn_menuKhach, BoxLayout.Y_AXIS));

        JButton bt_trangchu2 = cloneButton(btn_trangchu);
        JButton bt_datphong2 = cloneButton(btn_datphong);
        JButton bt_dangxuat2 = cloneButton(btn_dangxuat);
        JButton bt_thoat2 = cloneButton(btn_thoat);

        addButtonWithSpace(jpn_menuKhach, bt_trangchu2);
        addButtonWithSpace(jpn_menuKhach, bt_datphong2);
        addButtonWithSpace(jpn_menuKhach, bt_dangxuat2);
        addButtonWithSpace(jpn_menuKhach, bt_thoat2);
        jpn_menuKhach.add(Box.createVerticalGlue());

        // Style tất cả button
        styleAllButtons();

        // Add vào CardLayout
        jpn_west.add(jpn_menuFull, "FULL");
        jpn_west.add(jpn_menuKhach, "KHACH");
    }
    //tao ra ban copy button 
    private JButton cloneButton(JButton original) {
        JButton btn = new JButton(original.getText());

        // Copy ActionListener
        for (ActionListener al : original.getActionListeners()) {
            btn.addActionListener(al);
        }

        // Copy font, màu sắc
        btn.setFont(original.getFont());
        btn.setForeground(original.getForeground());
        btn.setBackground(original.getBackground());

        btn.setFocusPainted(false);
        btn.setBorderPainted(false);
        btn.setHorizontalAlignment(SwingConstants.LEFT);
        btn.setCursor(new Cursor(Cursor.HAND_CURSOR));

        // Copy size
        btn.setMaximumSize(new Dimension(230, 50));
        btn.setPreferredSize(new Dimension(230, 50));

        // Copy margin giống FULL
        btn.setBorder(BorderFactory.createEmptyBorder(10, 15, 10, 15));

        // Hover giống FULL
        btn.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn.setBackground(new Color(41, 128, 185));
            }

            @Override
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn.setBackground(new Color(52, 73, 94));
            }
        });

        return btn;
    }

    private void addButtonWithSpace(JPanel panel, JButton btn) {
        panel.add(Box.createVerticalStrut(10));
        panel.add(btn);
        btn.setAlignmentX(Component.CENTER_ALIGNMENT);
    }

    private void styleAllButtons() {
        JButton[] buttons = {
            btn_trangchu, btn_datphong, btn_quanlyphong,
            btn_quanlydatphong, btn_quanlykhachhang,
            btn_quanlydichvu,btn_dangxuat, btn_thoat
        };

        for (JButton btn : buttons) {
            btn.setFont(new Font("Segoe UI", Font.PLAIN, 15));
            btn.setForeground(Color.WHITE);
            btn.setBackground(new Color(52, 73, 94));
            btn.setFocusPainted(false);
            btn.setBorderPainted(false);
            btn.setHorizontalAlignment(SwingConstants.LEFT);
            btn.setCursor(new Cursor(Cursor.HAND_CURSOR));

            btn.setMaximumSize(new Dimension(230, 50));
            btn.setPreferredSize(new Dimension(230, 50));

            btn.setBorder(BorderFactory.createEmptyBorder(10, 15, 10, 15));

            btn.addMouseListener(new java.awt.event.MouseAdapter() {
                @Override
                public void mouseEntered(java.awt.event.MouseEvent evt) {
                    btn.setBackground(new Color(41, 128, 185));
                }

                @Override
                public void mouseExited(java.awt.event.MouseEvent evt) {
                    btn.setBackground(new Color(52, 73, 94));
                }
            });
        }
    }

    private void showMenuByQuyen() {
        CardLayout cl = (CardLayout) jpn_west.getLayout();
        if (quyenUser == 0) {
            cl.show(jpn_west, "FULL");
            lbl_tieude.setText("HỆ THỐNG QUẢN LÝ KHÁCH SẠN - NHÂN VIÊN");
        } else {
            cl.show(jpn_west, "KHACH");
            lbl_tieude.setText("HỆ THỐNG QUẢN LÝ KHÁCH SẠN - KHÁCH HÀNG");
        }
    }
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Form_zMain().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_dangxuat;
    private javax.swing.JButton btn_datphong;
    private javax.swing.JButton btn_quanlydatphong;
    private javax.swing.JButton btn_quanlydichvu;
    private javax.swing.JButton btn_quanlykhachhang;
    private javax.swing.JButton btn_quanlyphong;
    private javax.swing.JButton btn_thoat;
    private javax.swing.JButton btn_trangchu;
    private javax.swing.JPanel jpn_center;
    private javax.swing.JPanel jpn_header;
    private javax.swing.JPanel jpn_west;
    private javax.swing.JLabel lbl_tieude;
    // End of variables declaration//GEN-END:variables
}
